hystrix:
  image: fanfansama/hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery
discovery:
  image: fanfansama/discovery-microservice
  ports:
   - "8761:8761"
gateway:
  image: fanfansama/api-gateway-microservice
  ports:
   - "8181:8181"
  links:
   - discovery
   - sample
sample:
  image: fanfansama/sample-microservice
  ports:
   - "8282:8282"
  links:
   - discovery
