server:
  port: 8761

management:
  context-path: /manage


eureka:
  datacenter: talanlabs
  environment: github
  instance:
    hostname: localhost
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  # Stand-alone
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# DOCKER
#eureka:
#  instance:
#    hostname: discovery
#      defaultZone: http://discovery:${server.port}/eureka/