server:
  port: 10000

management:
  context-path: /manage

eureka:
  instance:
#    hostname: gateway
    hostname: localhost
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
      defaultZone: http://localhost:8761/eureka/